language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

virtualenv:
  system_site_packages: true

git:
  submodules: false

addons:
  apt:
    sources:
      - pov-wkhtmltopdf
    packages:
      - build-essential
      - libssl-dev
      - libffi-dev
      - python-dev
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - curl
      - nodejs
      - npm
      - python-ldap
      - python-psycopg2
      - python-simplejson
      - expect-dev
      - python-setuptools

language: python

python:
  - "2.7"

before_install:
  - export TRAVIS_DEBUG_MODE="1"
  - pip install urllib3[secure] --upgrade; true
  - pip install cryptography --no-binary --upgrade; true
  - pip install pyOpenSSL --upgrade; true
  - pip install cryptography --upgrade; true
  - pip install idna --upgrade; true
  - pip install certifi --upgrade; true
  - git clone https://github.com/zeroincombenze/tools.git ${HOME}/tools --depth=1
  - mv ${HOME}/tools/maintainer-quality-tools ${HOME}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - travis_install_env
  # - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  # - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  #   - travis_install_nightly
  - export EXCLUDE=hw_scanner,hw_escpos,document_ftp,delivery,stock_invoice_directly,claim_from_delivery

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - LINT_CHECK="1" LINT_CHECK_LEVEL="MINIMAL"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="website_signup_legal_page_required"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="website_signup_legal_page_required"
  - TESTS="1" ODOO_REPO="zeroincombenze/OCB"

  # Module website_seo_redirection intercepts any HTTP request, so if you see
  # some abnormal behavior in your controllers and suspect this is the guilty
  # module, just enable these 2 lines below to check that.
  # - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="website_seo_redirection"
  # - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="website_seo_redirection"

script:
  - travis_run_tests

after_success:
 - travis_after_tests_success
